### ISSUE TITLE
Allow to create a new cache factory

### ISSUE THREAD

**Issue by mrcmorales** [1up-lab/OneupFlysystemBundle#115]
Hi  @bytehead @sheeep ,

Should be interesting allow to create a new cache factory, I added a new service with tag oneup_flysystem.cache_factory but the problem is that the compiler pass is not getting this service because is in another bundle.

I think the problem is becacuse the compiler pass is creating a new container and not getting the application compiler.

What do you think ?

Thanks

**Comment by chosroes** [comment]
+1 The getFactories method in OneupFlysystemExtension.php should use the application container to allow custom cache factory.

**Comment by bytehead** [comment]
ping @sheeep

**Comment by bytehead** [comment]
Closed in favor of #127.
