### ISSUE TITLE
Add PhpRedisFactory class

### ISSUE THREAD

**Issue by chosroes** [1up-lab/OneupFlysystemBundle#125]
Hi,

The flysystem cached adapter library have a PhpRedis storage adapter that is missing in this bundle so I can't define a phpredis cache.
The change to add this new factory is pretty simple, is it possible to add it ?

I tried to add custom one, but as reported in #115, this is not possible.

Thank you.

**Comment by bytehead** [comment]
You're welcome to provide a pull request :)

**Comment by bytehead** [comment]
Close in favor of #126
