### ISSUE TITLE
Local adapter: changing directory via compiler pass

### ISSUE THREAD

**Issue by ghost** [1up-lab/OneupFlysystemBundle#13]
Hi, 

I need to change the directory value at runtime based on some infomation store in session. I thougth a compiler pass wuold do the job but it doesn't work.

oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: 'path_to_be_changed'

Inside a compiler pass:
$container->setParameter('oneup_flysystem.adapters.my_adapter.local.directory', 'my_dynamic_path');

What's the way to achieve that?

**Comment by gnutix** [comment]
@matteomoretti any chance you could share some code ? Seems like I'm going into the same rabbit hole...
