### ISSUE TITLE
Error on configuration

### ISSUE THREAD

**Issue by pjarmalavicius** [1up-lab/OneupFlysystemBundle#149]
->cannotBeEmpty() is not applicable to concrete nodes at path "oneup_flysystem.filesystems..stream_wrapper.configuration.permissions" in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Builder/ArrayNodeDefinition.php:494

Since symfony 3.4 cannotBeEmpty can not be used on array nodes. [Symfony commit](https://github.com/symfony/config/commit/22be0993aac292e012efaf9ec9448a5abe9fa1f1)

**Comment by bytehead** [comment]
Fixed via #154.
