### ISSUE TITLE
Add support for disable_asserts option

### ISSUE THREAD

**Issue by francoispluchino** [1up-lab/OneupFlysystemBundle#150]
Since Flysystem 1.0.26, the new option `disable_asserts` is present to improve the performance:

```php
new League\Flysystem\Config;
new League\Flysystem\Filesystem;

$local = Filesystem($localAdapter, new Config([
    'disable_asserts' => true,
]));
```
See the official [doc](https://flysystem.thephpleague.com/performance).

Will you add this option in the bundle configuration?

**Comment by bytehead** [comment]
I like the idea 👍

**Comment by bytehead** [comment]
It's just missing in the documentation, it's already implemented since https://github.com/1up-lab/OneupFlysystemBundle/pull/140 :)

**Comment by francoispluchino** [comment]
Sorry, I thought I was using the latest version, but it was not... Thank you!

**Comment by bytehead** [comment]
You're welcome!
