### ISSUE TITLE
Create symfony/recipes-contrib recipe

### ISSUE THREAD

**Issue by bytehead** [1up-lab/OneupFlysystemBundle#160]
See https://github.com/symfony/recipes-contrib/issues/146

**Comment by liederer** [comment]
I've opened a PR: https://github.com/symfony/recipes-contrib/pull/255

**Comment by bytehead** [comment]
Thank you!

**Comment by bytehead** [comment]
Receipe is done: https://github.com/symfony/recipes-contrib/pull/255.
Props goes out to @liederer! 🎉
