### ISSUE TITLE
Cherry-Pick config fix to 1.x

### ISSUE THREAD

**Issue by cedricziel** [1up-lab/OneupFlysystemBundle#161]
6144216516f78e8bc33b3e3b736e7fcd67b1d0ed fixes a deprecation with Symfony 3.4. Could you cherry-pick it and release another bugfix version for 1.x?

**Comment by bytehead** [comment]
I've just released [`1.14.1`](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/1.14.1).

**Comment by cedricziel** [comment]
Great, thx a bunch!

**Comment by bytehead** [comment]
You're welcome, thanks for reporting!
