### ISSUE TITLE
How to log e.g. 404 errors

### ISSUE THREAD

**Issue by benr77** [1up-lab/OneupFlysystemBundle#166]
I'm storing a load of images on S3 via Flysystem.

Is it possible to arrange for e.g. missing images to be logged via monolog.

I'm also using VichUploader and LiipImagine to manage the images? Perhaps these are better points to implement logging?

Thanks for any suggestions

**Comment by sheeep** [comment]
Hmm.. I'd say to either add a check in your userland code or double check VichUploaderBundle/LiipImageBundle for such a possibility. A quick look at the Flysystem API strongly suggests that there is no such thing as a NotFoundEvent thrown.

**Comment by benr77** [comment]
Both VichUploader and LiipImagine throw exceptions when resources are missing. 
https://github.com/dustin10/VichUploaderBundle/issues/849
