### ISSUE TITLE
deprecation logged in Symfony 3.4.6

### ISSUE THREAD

**Issue by PhilETaylor** [1up-lab/OneupFlysystemBundle#167]
Followed all install instructions - it all works well but I get this deprecation logged in Symfony 3.4.6

`
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "oneup_flysystem.mycustom_filesystem" service to "League\Flysystem\Filesystem" instead.
`

**Comment by PhilETaylor** [comment]
2018? no action? wow.. ok to close, Im now using Symfony 5.2 so I could never replicate now even if I wanted. No bother :)

**Comment by bytehead** [comment]
No worries, the newest release is compatible with Symfony 5.x anyway.
