### ISSUE TITLE
Upgrading from version 2 to 3

### ISSUE THREAD

**Issue by larzuk91** [1up-lab/OneupFlysystemBundle#175]
Hello, this is not actually a bug report but I couldn't find a CHANGELOG or something in your releases section that enumerates the BC breaks from version 2 to 3. I'm about to do the upgrade and would be nice to know which things does not work anymore in the newest version. 
Any help in this matter is really appreciated. Thanks!

**Comment by larzuk91** [comment]
Ohh, cool... so there aren't any BC breaks from version 2 to 3

**Comment by bytehead** [comment]
I could not find any issue or PR related to this.
Here is the [compare view](https://github.com/1up-lab/OneupFlysystemBundle/compare/2.0.1...3.0.2).

**Comment by larzuk91** [comment]
It looks solid! I'll give it a try as soon as I can. Thanks for your support :)

**Comment by bytehead** [comment]
Yeah, let me know if it works without any hassle!
No worries, you're welcome :)

**Comment by larzuk91** [comment]
Ok, I just upgraded to the latest version and ran my tests - it worked!

Thanks man :)
