### ISSUE TITLE
MountManager injection in Symfony 4.3

### ISSUE THREAD

**Issue by tobikummer** [1up-lab/OneupFlysystemBundle#195]
I updated our distribution from Symfony 3.4 to 4.3. 

We have an service (and not a controller) with handles our assets.

In Symfony 3.4 it was possible to inject the MountManager via DI and get the filesystem like
`$this->mountManager->getFilesystem('cache)`

In Symfony 4.3, I have to inject the container (what is bad practice) and then access the MountManager with
`$this->container->get('oneup_flysystem.mount_manager')->getFilesystem('cache')`

Is there another possibility without injecting the container (in a service)?

**Comment by bytehead** [comment]
Why can't you inject the MountManager via DI anymore?

**Comment by tobikummer** [comment]
If I use DI and `$this->mountManager->getFilesystem('cache)`, the whole configuration in my "/config/packages/oneup_flysystem.yaml" is ignored an it throws an error that I don't have a filesystem with prefix "cache".
If I use `$this->container->get('oneup_flysystem.mount_manager')->getFilesystem('cache')` all works fine and my config works properly. 
All done in a service, not in a controller.

**Comment by bytehead** [comment]
Can't reproduce this. How does your config look like?

**Comment by tobikummer** [comment]
`# OneupUploaderBundle
oneup_flysystem:
    adapters:
        # Private storage adapters
        cache_adapter:
            local:
                directory: "%kernel.project_dir%/assets/private/cache"
        general_adapter:
            local:
                directory: "%kernel.project_dir%/assets/private/general"
        publications_adapter:
            local:
                directory: "%kernel.project_dir%/assets/private/publications"
        releases_adapter:
            local:
                directory: "%kernel.project_dir%/assets/private/releases"

        # Public storage adapters
        public_releases_adapter:
            local:
                directory: "%kernel.project_dir%/assets/public/releases"

    filesystems:
        # Private flysystems
        cache:
            adapter: cache_adapter
            visibility: private
            mount: cache
        general:
            adapter: general_adapter
            visibility: private
            mount: general
        publications:
            adapter: publications_adapter
            visibility: private
            mount: publications
        releases:
            adapter: releases_adapter
            visibility: private
            mount: releases

        # Public flysystems
        public_releases:
            adapter: public_releases_adapter
            visibility: public
            mount: public_releases`

**Comment by bytehead** [comment]
```php
$fs = $this->mountManager->getFilesystem('cache');
dump($fs);
```
will output
```
League\Flysystem\Filesystem^ {#246
  #adapter: League\Flysystem\Adapter\Local^ {#247
    #pathSeparator: "/"
    #permissionMap: array:2 [
      "file" => array:2 [
        "public" => 420
        "private" => 384
      ]
      "dir" => array:2 [
        "public" => 493
        "private" => 448
      ]
    ]
    #writeFlags: 2
    -linkHandling: 2
    #pathPrefix: "/Users/davidgreminger/dev/flysystem-test/assets/private/cache/"
  }
  #plugins: []
  #config: League\Flysystem\Config^ {#248
    #settings: array:2 [
      "visibility" => "private"
      "disable_asserts" => false
    ]
    #fallback: null
  }
}
```

How does your `services.yml` file look?

**Comment by bytehead** [comment]
Otherwise just pass by in our office and we can have a look at it together - coffee included 😎

**Comment by tobikummer** [comment]
very strange... I'll debug once again and check for weird things. If not successful, I'll come back to your ☕️-offer 😏

**Comment by bytehead** [comment]
you're welcome 👍
