### ISSUE TITLE
Support the Replica adapter

### ISSUE THREAD

**Issue by sheeep** [1up-lab/OneupFlysystemBundle#20]
See: https://github.com/thephpleague/flysystem#replicateadapter-setup

**Comment by alexander-schranz** [comment]
any updates to this one?

**Comment by cklm** [comment]
any updates here?

**Comment by bytehead** [comment]
Not yet. Pull requests are always welcome :)

**Comment by bytehead** [comment]
Can you test the [feature/replica-adapter](https://github.com/1up-lab/OneupFlysystemBundle/tree/feature/replica-adapter) branch?

**Comment by bytehead** [comment]
Implemented via #145
