### ISSUE TITLE
Add flysystem adapter for AsyncAws S3

### ISSUE THREAD

**Issue by aziz-harazi** [1up-lab/OneupFlysystemBundle#208]
Hello, does the package will use async-aws/flysystem-s3  dependency instead of league/flysystem-aws-s3-v2soon ?

Thank you

**Comment by bytehead** [comment]
It actually suggests to use `league/flysystem-aws-s3-v3` if you want to use v3: https://github.com/1up-lab/OneupFlysystemBundle/blob/master/composer.json#L61

**Comment by aziz-harazi** [comment]
Thank you for your response. 
with oneup/flysystem-bundle, we have dependency with flysystem-aws-s3-v2(3) which have dependency aws/aws-sdk-php which is loading all services. 

 async-aws/flysystem-s3 has dependency with async-aws/core and async-aws/s3 we will not have to get all aws services.

Thank you and have a good day

**Comment by aziz-harazi** [comment]
Are you going to include async-aws/flysystem-s3, in a future version ?

**Comment by bytehead** [comment]
Yes that could be an enhancement!

**Comment by bytehead** [comment]
I just don't have any time plan as my free time at the moment is quite limited.

**Comment by bytehead** [comment]
You could try to add your custom filesystem with https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_custom.md and https://async-aws.com/integration/flysystem.html

**Comment by aziz-harazi** [comment]
Thank you very much. I'm going to try it.

**Comment by bytehead** [comment]
Did you end up successfully trying it via custom adapter?

**Comment by aziz-harazi** [comment]
Hello, i'm coing to fix or this week. I will sens a pull request to you

Le lun. 25 mai 2020 à 15:29, David Greminger <notifications@github.com> a
écrit :

**Comment by Nyholm** [comment]
I added a PR for this in #209

**Comment by bytehead** [comment]
Thank you Tobias! I'll check the PR asap :)

**Comment by bytehead** [comment]
Closed in favor of #209
