### ISSUE TITLE
Support Http adapter

### ISSUE THREAD

**Issue by sheeep** [1up-lab/OneupFlysystemBundle#21]
As long as it will be merged of course.
https://github.com/thephpleague/flysystem/pull/244

**Comment by sheeep** [comment]
@frankdejonge As far as I can tell the GuzzleAdapter in `thephpleague/flysystem http-guzzle-adapter` was meant to be an HTTP adapter but was never merged. Is this still a thing?

**Comment by frankdejonge** [comment]
@sheeep nope, nobody ended up wanting to maintain it. Or use it for that matter, I'd close this issue.

**Comment by bytehead** [comment]
Thanks for your quick response!

**Comment by frankdejonge** [comment]
@sheeep welcome :) any time!
