### ISSUE TITLE
league/flysystem-adapter-test-utilities comptabiliy with oneup/flysytstem:3.5.0

### ISSUE THREAD

**Issue by aziz-harazi** [1up-lab/OneupFlysystemBundle#210]
Hello, 
I would like to use async-aws/flysystem-s3 with league/flysystem-adapter-test-utilities: 2.x-dev (dev dependency). 

But it seems that to use  league/flysystem-adapter-test-utilities: 2.x-dev we need league/flysystem: 2.0.0-alpha.3 which is not compatible with oneup/flysystem-bundle.

Could you help me. please ?

**Comment by bytehead** [comment]
I think this belongs to https://github.com/async-aws/flysystem-s3, as it is required here: https://github.com/async-aws/flysystem-s3/blob/0.4.0/composer.json#L29. 

This bundle only requires `async-aws/flysystem-s3` in version `^0.4.0`.

Why should this not be compatible? In case of an error, what is the message?

**Comment by aziz-harazi** [comment]
Yes but if I want to use league/flysystem-adapter-test-utilities I need to install oneup/flysystem-bundle
I have no error but I have some problems with phpunit since I installed the new package,The problem could be somewhere else. I continue investigation

**Comment by bytehead** [comment]
This will be covered by upcoming release 4.x
