### ISSUE TITLE
Unrecognized option "directory" under local adapter when install the bundle with symfony

### ISSUE THREAD

**Issue by wengtytt** [1up-lab/OneupFlysystemBundle#230]
I'd like to install version 4.x bundle, but the Symfony recipe creates the config file using version 3. It ends up the error "Unrecognized option 'directory" under "oneup_flysystem.adapters.default_adapter.local". And the composer.json got reverted.

**Comment by bytehead** [comment]
I've made a PR for the version 4.x recipe: https://github.com/symfony/recipes-contrib/pull/1100

**Comment by bytehead** [comment]
Maybe you can approve over there :)

**Comment by bytehead** [comment]
Should work now as the recipe for 4.x is available now! Please reopen, if it still won't work :)
