### ISSUE TITLE
Misspell about the `DefaultVisibility` option

### ISSUE THREAD

**Issue by yoan-evaneos** [1up-lab/OneupFlysystemBundle#255]
### Question

I've detected that the option that allow us to define the default visibility of the FS is spelt `DefaultVisiblity` into the config files and the implementation

Further More, could you add documentation about this option ? I read the implementation to determine how I could use it to propagate a `NoPredefinedVisibility` value for GCS FS. I think that it could be very useful to have a complete example about those option.

Thanks.

|    Q        |   A
|------------ | ------
| Version     | 4.2.0

**Comment by bytehead** [comment]
Thanks for reporting. I'll check the bug and will provide a fix 👍 

Would it possible for you to provide a pull request regarding the documenation, as you already have some experience with it (and possibly a running config)?

**Comment by bytehead** [comment]
`4.11.3` with the fix is now available.
