### ISSUE TITLE
Symfony 6.0 compatibility

### ISSUE THREAD

**Issue by ltlsquare** [1up-lab/OneupFlysystemBundle#256]
### Bug Report
|------------ | ------
| BC Break    | No
| Version     | 4.2.0

#### Summary

Upgrade to Symfony 5.4 works perfectly well. upgrading to the next major version Symfony 6.0 results in unresolvable set of packages.

Problem 1
    - oneup/flysystem-bundle[4.0.0, ..., 4.2.0] require symfony/config ^4.4 || ^5.0 -> found symfony/config[v4.4.0, ..., v4.4.34, v5.0.0, ..., v5.4.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires oneup/flysystem-bundle ^4.0 -> satisfiable by oneup/flysystem-bundle[4.0.0, ..., 4.2.0].

#### How to reproduce

Set up a brand new symfony project:
run the follwing commands in the console:

1. symfony new flyupsix_point_o
2. cd flyupsix_point_o
3. composer require oneup/flysystem-bundle -W

this will result in: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires oneup/flysystem-bundle ^4.2 -> satisfiable by oneup/flysystem-bundle[4.2.0].
    - oneup/flysystem-bundle 4.2.0 requires symfony/config ^4.4 || ^5.0 -> found symfony/config[v4.4.0, ..., v4.4.34, v5.0.0, ..., v5.4.0] but the package is fixed to v6.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by bytehead** [comment]
Will be fixed soon by #257.

**Comment by bytehead** [comment]
Please update to [4.3.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/4.3.0).
