### ISSUE TITLE
Config Adapter sftp load PhpseclibV2 no PhpseclibV3

### ISSUE THREAD

**Issue by pacofall** [1up-lab/OneupFlysystemBundle#270]
### Bug Report
Symfony 6 and league/flysystem-sftp-v3

Attempted to load class "SftpAdapter" from namespace "League\Flysystem\PhpseclibV2".

In adapter.xml still:
        <service id="oneup_flysystem.adapter.sftp" class="League\Flysystem\PhpseclibV2\SftpAdapter" abstract="true" public="false">

and class SftpFactory implements AdapterFactoryInterface use:
use League\Flysystem\PhpseclibV2\SftpConnectionProvider;

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | x.y.z

**Comment by pacofall** [comment]
Add a new adapter "sftpv3" will be welcome.

**Comment by bytehead** [comment]
We'll have to add a new adapter `sftpv3` otherwise we're not backwards compatible anymore.

**Comment by bytehead** [comment]
Which PHP version are you using?

**Comment by pacofall** [comment]
Thanks for reply.. on PHP 8.1; which require League\Flysystem\PhpseclibV3......

**Comment by bytehead** [comment]
Ok 👍 I'll prepare a release `4.6.0` which replaces PhpseclibV2 with PhpseclibV3 (PHP 7 support was dropped for `4.5.0` anyway.

**Comment by bytehead** [comment]
@pacofall any reason why are you not using `league/flysystem-sftp` as suggested by the bundle?

**Comment by pacofall** [comment]
It s solution we used currently according https://flysystem.thephpleague.com/docs/adapter/sftp-v3/.

We get issues by config.yaml way  which use default config adapter.

# app/config/config.yml
oneup_flysystem:
    adapters:
        my_adapter:
            sftp:
                options:
                    host: 'ftp.domain.com'
                    username: 'foo'
                    root: '/upload'

**Comment by 24s-dcognata** [comment]
✋🏻 @bytehead , any news for a fix ?

**Comment by bytehead** [comment]
@24s-dcognata could you test PR #272?

**Comment by 24s-dcognata** [comment]
Hi @bytehead, we'll try to test this PR on our app today or by next week.

**Comment by bytehead** [comment]
@24s-dcognata thanks 🙏  let me know the outcome ☺️

**Comment by 24s-dcognata** [comment]
Hi @bytehead 

Sorry for the wait,

we tested your PR, everything works on our application. 🎉 

- The communication with the server works and the files are created correctly.

**Comment by bytehead** [comment]
@24s-dcognata `4.6.0` is released.
