### ISSUE TITLE
Upgrade path v3.7.1 to v4

### ISSUE THREAD

**Issue by mvhirsch** [1up-lab/OneupFlysystemBundle#305]
### Question

|    Q        |   A
|------------ | ------
| Version     | 3.7.1

I'm working on a project which still uses v3.7.1. I noticed this bundle published v4 a while back, but there is no changelog nor a upgrade path.

Please document what steps need to be taken to upgrade to v4+.

**Comment by bytehead** [comment]
It is basically just the update to Flysystem v2 and v3 (see https://flysystem.thephpleague.com/docs/what-is-new/)
