### ISSUE TITLE
Duplicated factory service id

### ISSUE THREAD

**Issue by reidd** [1up-lab/OneupFlysystemBundle#32]
The awss3 factory service name is duplicated under the `GridFsFactory`, see link below.

This is causing an error `[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "awss3" under "oneup_flysystem.adapters.my_adapter"`

https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/config/factories.xml#L35

**Comment by bytehead** [comment]
Fixed in https://github.com/1up-lab/OneupFlysystemBundle/commit/91f507ff6fb3db502dd75bcacae23b6dc8f8640d. Thanks!
