### ISSUE TITLE
Bump version requirement of league/flysystem

### ISSUE THREAD

**Issue by yellow1912** [1up-lab/OneupFlysystemBundle#34]
Right now the league/flysystem-aws-s3 both v2 and v3 require ~1.0 but this bundle is using ~0.4 which result in unresolveable conflict. Can you please bump requirement?

**Comment by bytehead** [comment]
Thanks for the notice. 
There are a lot of changes in league/flysystem 1.0.0, so we can't just bump the requirement.
A new version is currently under development.

**Comment by yellow1912** [comment]
Super. I just noticed the new brand. Will watch it closely.

**Comment by yellow1912** [comment]
@bytehead Since I need this to work asap for my work, I would love to help you to speed up the release of the 1.x-dev branch. I took a look at the branch and have a few questions for you so I can know the direction you want to take and can send pull request to you

1. I see you are requiring many 'adapters' in the composer. I would like to propose removing all that (like what you have in the master branch), let the users choose what they want instead?
2. I see you are requiring both aws s3 v2 and v3 at the same time, I think this will cause a conflict with composer?
3. I would like to know the direction you want to take for aws v2 and v3 adapter file. Do you want to create 2 different adapters for it? Or Perhaps you want to allows the users to specify the version they want to use in the config instead?

``
oneup_flysystem:
    adapters:
        s3:
            awss3v3:
                client: acme.s3_client
                bucket: ~
                prefix: ~
``

VS

``
oneup_flysystem:
    adapters:
        s3:
            awss3:
                version: v3
                client: acme.s3_client
                bucket: ~
                prefix: ~

**Comment by sheeep** [comment]
> I see you are requiring many 'adapters' in the composer. I would like to propose removing all that (like what you have in the master branch), let the users choose what they want instead?

Are you sure you're talking about the composer.json of this bundle? Because it just [requires](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/composer.json#L17) the `symfony/framework-bundle` and `league/flysystem`.

> I would like to know the direction you want to take for aws v2 and v3 adapter file. Do you want to create 2 different adapters for it? Or Perhaps you want to allows the users to specify the version they want to use in the config instead?

I'm all for 2 different adapters. If they changed anything in the API we end up with endless version-distinguishing `if`s. What do you think?

**Comment by sheeep** [comment]
> Are you sure you're talking about the composer.json of this bundle? Because it just requires the symfony/framework-bundle and league/flysystem.

Ah sorry, wrong branch. Should check the commit history first.

**Comment by yellow1912** [comment]
@sheep Perfect, I also opt for that option :+1:

**Comment by bytehead** [comment]
@yellow1912 is it possible for you to test the [1.x-dev branch](https://github.com/1up-lab/OneupFlysystemBundle/tree/1.x-dev) with your AWS S3 Adapter?

**Comment by bytehead** [comment]
@yellow1912 please check the [1.0.0-beta](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/v1.0.0-beta)

**Comment by yellow1912** [comment]
Superb. Seems to work all nicely. Thank you.
