### ISSUE TITLE
A more flexible way to attach plugins to filesytem

### ISSUE THREAD

**Issue by yellow1912** [1up-lab/OneupFlysystemBundle#40]
Say if I have pluginA that I want to attach to 3 (out of n) filesystems, I have to create 3 services separately. Maybe I'm mistaken but it should be possible to re-use the same plugin service for any number of filesystem. 

My proposal is rather simple: allow passing the filesystem ids as a string (comma separated)

``` xml
<service id="assetic.filesystem.plugin.awss3_url" class="%assetic.filesystem.plugin.awss3_url.class%">
            <tag name="oneup_flysystem.plugin" filesystem="s3,local,remote" />
        </service>
```

Then in the compiler pass we can easily explode the string then loop through the array.

What do you think? I can implement it and send a PR, it's quite easy.

**Comment by yellow1912** [comment]
In addition, it may be interesting to consider adding another attribute to define the type of filesystem you want to associate the plugin with. During my day to day usage of filesystem I have noticed that I usually need to write plugin to add additional features to a specific filesystem adapter. (for example, I want to add getUrl to all s3 adapter filesystem). So it may make sense to also allow something like this:

```xml
<service id="assetic.filesystem.plugin.awss3_url" class="%assetic.filesystem.plugin.awss3_url.class%">
            <tag name="oneup_flysystem.plugin" adapter="awss3v2,awss3v3" />
        </service>
```

**Comment by bytehead** [comment]
Plugins won't be supported in V2 of league/flysystem.
