### ISSUE TITLE
Confusing documentation for plugins

### ISSUE THREAD

**Issue by rossdeane** [1up-lab/OneupFlysystemBundle#43]
The docs for creating a plugin state that you should tag your service with `oneup_flysystem.filesystem_plugin` yet it seems its actually looking for `$plugins = $container->findTaggedServiceIds('oneup_flysystem.plugin');`

**Comment by sheeep** [comment]
The plugin system gets a reshape (https://github.com/1up-lab/OneupFlysystemBundle/pull/42), but you're right. Thanks for reporting.

**Comment by bytehead** [comment]
The plugin system is gone in v2 of league/flysystem.
