### ISSUE TITLE
 Class 'League\Flysystem\Cached\CachedAdapter' not found

### ISSUE THREAD

**Issue by taylor19882002** [1up-lab/OneupFlysystemBundle#47]
PHP Fatal error:  Class 'League\Flysystem\Cached\CachedAdapter' not found in ../app/cache/dev/appDevDebugProjectContainer.php

config.xml
oneup_flysystem:

    filesystems:
        acme:
            adapter: my_adapter
            cache: my_cache
            alias: ~
            mount: ~
    cache:
        my_cache:
            memory: ~
    adapters:
        my_adapter:
            local:
                directory: %kernel.root_dir%/../push_response

I have no idea, why the cache file not include the adapter class in current latest version. But pervious version it's works.

**Comment by bytehead** [comment]
@taylor19882002 which versions are you using?

**Comment by taylor19882002** [comment]
symfony 2.3
OneupFlysystemBundle 4.2 ???

**Comment by bytehead** [comment]
Ok, looks like you are using `"league/flysystem": "~1.0"`. Try to update `OneupFlysystemBundle` to version `"oneup/flysystem-bundle": "1.0.0-beta"`, there is `League\Flysystem\Cached\CachedAdapter` available.

**Comment by bytehead** [comment]
You should require the new released `1.0.0` in your `composer.json` 
```
...
"require": {
        ...
        "oneup/flysystem-bundle": "1.0.0",
        ...
    },
...
```

**Comment by Romerolweb** [comment]
Hi, have a nice day,
What is the version for right now?

**Comment by bytehead** [comment]
See https://packagist.org/packages/oneup/flysystem-bundle, 3.5.0 🙃
