### ISSUE TITLE
move to psr4

### ISSUE THREAD

**Issue by cordoval** [1up-lab/OneupFlysystemBundle#50]

**Comment by cordoval** [comment]
i can do this so you can tag it if you want right after this

**Comment by cordoval** [comment]
bump @sheeep let's wait for travis

**Comment by cordoval** [comment]
@bytehead do you think we can tag anew since this would be a nice to have in a tagged version to use right away?

**Comment by bytehead** [comment]
@cordoval there is still a bug pending (#47) that I would like to fix before tagging a new version (actually 1.0.x). 
But I could provide a 0.5.x directly from 0.4.2 with the PSR-4 fix if you're interested.

**Comment by bytehead** [comment]
There you go: [0.5.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/v0.5.0)

**Comment by cordoval** [comment]
exactly right, you read me perfectly, sometimes i see that in FOSS a lot, even coming from people that i want to respect :older_man: their decision, my question is just to bump it, not to create a big release. It is never my intention. even a minor number 0.4.999999999 will suffice. But yeah people just don't get it.

Glad you got it and now we are flying :airplane: :older_man:  :+1: thanks!
