### ISSUE TITLE
question on install

### ISSUE THREAD

**Issue by cordoval** [1up-lab/OneupFlysystemBundle#52]
i ran composer and saw

```
  - Removing league/flysystem (1.0.3)
  - Installing league/flysystem (0.5.12)
    Downloading: 100%

  - Removing oneup/flysystem-bundle (dev-master)
  - Installing oneup/flysystem-bundle (v0.5.0)
    Downloading: 100%
```

wonder if you know why flysystem went back to 0.5.12

**Comment by bytehead** [comment]
That's because `0.x`-branch uses `"league/flysystem": "~0.4"`, while the new `1.x`-branch uses `"league/flysystem": "~1.0"`.

**Comment by cordoval** [comment]
oh no why multiple branches of a bundle? can't believe it, i think you should just tag linearly please :older_man: but feel free to do it as you wish. i just think is not good at all for the reasons we are currently facing and others.

**Comment by bytehead** [comment]
Here it is: [1.0.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/v1.0.0).
