### ISSUE TITLE
Working with big files 100 MO - Error: Allowed memory size

### ISSUE THREAD

**Issue by ychoucha** [1up-lab/OneupFlysystemBundle#58]
well i m try to work with files > 100 Mo 

i have this error : 

FatalErrorException: Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 106839070 bytes) in /var/www/html/demo-Symfony2-Flysystem/Symfony/vendor/league/flysystem/src/Adapter/Local.php line 165

how fix that please ?

**Comment by bytehead** [comment]
Check your `PHP.ini` settings for `memory_limit` – the bundle itself has no limitation.

**Comment by ychoucha** [comment]
so i do that  : 
memory_limit = -1

because in documentaito says : 
Note that to have no memory limit, set this directive to -1.  here --> http://php.net/manual/en/ini.core.php#ini.memory-limit

but i stilla have this error with flysystem : 

Fatal error: Out of memory (allocated -2101608448) (tried to allocate 269777424 bytes) in ...ue/flysystem/src/Adapter/Zip.php on line 61

**Comment by bytehead** [comment]
You're probably running out of physical memory. Your system allocated already about 2.1GB. How much RAM do you actually have available?
