### ISSUE TITLE
Simplify the process of adding custom adapter

### ISSUE THREAD

**Issue by yellow1912** [1up-lab/OneupFlysystemBundle#63]
Right now it seems like it's not easy to add new adapter because the AdapterFactories are defined in this Bundle's DI folder. It should be easier to define a new custom adapter else where and simply refer to it in the config.

**Comment by yellow1912** [comment]
I think there are 2 options to get around this:

1. Option 1: we can define the list of bundles that will extend the factories (to be even more generic we can even allow passing the direct path to the extra config files). Then we will use this definition to load the extra config files and get the list of external factories. 

Pros: easy to implement without much changes in the code
Cons: can look a bit ugly

2. Option 2: we will have to bypass the validation of configurations passed through us and only validate in the CompilerPass. The reason is that in the CompilerPass phase we have access to all defined services and paramters (including the ones defined in other bundles as well)

Pros: without having to manually add the path to external config, we simply have to tag our factories
Cons: we will have to move lots of code into the CompilerPass

**Comment by yellow1912** [comment]
I have working code for this, will open a pull request this week.

**Comment by bytehead** [comment]
Always welcome due to our limited time ;-)

**Comment by yellow1912** [comment]
Pull request sent :)

**Comment by bytehead** [comment]
See https://github.com/1up-lab/OneupFlysystemBundle/pull/65#issuecomment-121186847

**Comment by BenjaminPaap** [comment]
I would :heart: to see this one getting merged. Need this to add the memory adapter for testing purposes.
