### ISSUE TITLE
Fatal Error: CachedAdapter not found

### ISSUE THREAD

**Issue by mrcmorales** [1up-lab/OneupFlysystemBundle#93]
Hi,

I updated the version and I get this error: PHP Fatal error:  Class 'League\Flysystem\Cached\CachedAdapter' not found 

I have this versions in composer.json:
```
"oneup/flysystem-bundle"                            : "1.1.0",
"league/flysystem-aws-s3-v2"                        : "~1.0",
```
Where is the problem ?

Thanks

**Comment by bytehead** [comment]
Try `oneup/flysystem-bundle": "~1.1"` and run a `composer update`.

**Comment by mrcmorales** [comment]
hi @bytehead 

I updated, but the same problem.

Now the version installed is: oneup/flysystem-bundle (1.3.0)

Thanks

**Comment by bytehead** [comment]
I can definitely not reproduce this. Where does this error occur?

**Comment by mrcmorales** [comment]
@bytehead This error occurs cleaning the cache of symfony.

I'm using symfony 2.6.* and the versions of flysystem installed are:

```
league/flysystem                                 1.0.18             
league/flysystem-aws-s3-v2                       1.0.3              
oneup/flysystem-bundle                           1.3.0   
```
Thanks

**Comment by bytehead** [comment]
Do you have any error stack?

**Comment by mrcmorales** [comment]
@bytehead not, this is the error:

```
Attempted to load class "CachedAdapter" from namespace "League\Flysystem\Cached".
Did you forget a "use" statement for another namespace?
```

**Comment by bytehead** [comment]
Is `league/flysystem-cached-adapter` installed?

**Comment by bytehead** [comment]
otherwise you should add it:
`composer require league/flysystem-cached-adapter`

**Comment by mrcmorales** [comment]
@bytehead now, I added league/flysystem-cached-adapter

Thanks

**Comment by bytehead** [comment]
No worries - you're welcome! Thanks for using the bundle!
