### ISSUE TITLE
Setting permissions of Local adapter

### ISSUE THREAD

**Issue by systemist** [1up-lab/OneupFlysystemBundle#94]
Flysystem Local adapter constructor accepts $permissions argument:
    
    public function __construct($root, $writeFlags = LOCK_EX, $linkHandling = self::DISALLOW_LINKS, array $permissions = [])

Is there a way to set permissions in OneupFlysystemBundle ?

**Comment by andreas-glaser** [comment]
+1 Having the same issue

**Comment by andreas-glaser** [comment]
I have implemented the feature in #101

**Comment by bytehead** [comment]
Fixed by #101.
