### ISSUE TITLE
How to triggered AWSS3v3 server with akeneo-pim?

### ISSUE THREAD

**Issue by srikant-dubey** [1up-lab/OneupFlysystemBundle#99]
We have configured the ASWS3v3 as per the documentation provided ([http://docs.akeneo.com/latest/cookbook/product_asset/how_to_connect_to_an_external_server.html#quick-overview]). How can we triggered the assets to AWS bucket?

**Comment by sheeep** [comment]
Well. I guess this should be as easy as configure an [AWS-Adapter](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_awss3.md) instead of an SFTP one. Maybe the devs from akeneo can help you, as this is a bit out of scope for this bundle. :)
